apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image }}:{{ .Values.backend.tag }}"
          env:
            - name: DATABASE_URL
              value: "postgres://{{ .Values.database.user }}:{{ .Values.database.password }}@db:5432/{{ .Values.database.dbName }}"
            - name: CORS_ALLOWED_ORIGINS
              value: "http://54.86.145.100:30768"
            - name: FRONTEND_URL
              value: "http://54.86.145.100:30768"
            # Add other existing vars here...
