apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image }}:{{ .Values.frontend.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          # Ensure this variable is present and updated
          env:
            - name: VITE_API_URL
              value: "http://{{ .Values.global.domain }}:30768/api/"
