apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: n8n
spec:
  serviceName: "n8n"
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    spec:
      containers:
        - name: n8n
          image: "{{ .Values.n8n.image }}:{{ .Values.n8n.tag }}"
          env:
            - name: WEBHOOK_URL
              value: "http://54.86.145.100:30768/n8n/"
            - name: N8N_EDITOR_BASE_URL
              value: "http://54.86.145.100:30768/n8n/"
          volumeMounts:
            - name: n8n-data
              mountPath: /home/node/.n8n
  volumeClaimTemplates:
    - metadata:
        name: n8n-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
